module:
  _target_: biscuits.pl_modules.pl_module.CycleGANLightningModule

model:
  _target_: biscuits.modules.CycleGAN

  # resnet_depth: 32

  conv_init: 
    method: "normal"
    range: [0, 0.02]

  batchnorm_init:
    parameters:
      method: "uniform"
      range: [0, 1]
    bias: "0"
  
  instancenorm_init:
    parameters:
      method: "uniform"
      range: [0, 1]
    bias: "0"

  # lin_init_method: "he_kaiming_normal"

  conv_freeze_parameters: False

  batchnorm_freeze_parameters: False

  instancenorm_freeze_parameters: False

  # lin_freeze_parameters: False

  # dropout_probability: 0.5
  # dropout2d_probability: 0.2

  optimizer: 
    _target_: torch.optim.SGD
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-4

  # lr_scheduler:
  #   _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  #   T_0: 10
  #   T_mult: 2
  #   eta_min: 0 # min value for the lr
  #   last_epoch: -1
  #   verbose: False
