module:
  _target_: biscuits.pl_modules.pl_module.CycleGANLightningModule

model:
  _target_: biscuits.modules.CycleGAN

  num_residual_blocks: 6

  conv_init: 
    method: "normal"
    range: [0, 0.02]

  batchnorm_init:
    parameters:
      method: "uniform"
      range: [0, 1]
    bias: "0"
  
  instancenorm_init:
    parameters:
      method: "uniform"
      range: [0, 1]
    bias: "0"

  input_shape: (${data.num_channels}, ${data.img_height}, ${data.img_width})

  # lin_init_method: "he_kaiming_normal"

  conv_freeze_parameters: True

  # batchnorm_freeze_parameters: False

  instancenorm_freeze_parameters: False # ignored if instancenorm_affine = False!
  instancenorm_affine: True

  # lin_freeze_parameters: False

  # dropout_probability: 0.5
  # dropout2d_probability: 0.2

  lambda_cyc: 5.0
  lambda_id: 10.0

  log_images: 50

  optimizer: 
    _target_: torch.optim.Adam
    lr: 0.1
    beta_1: 0.5
    beta_2: 0.999
    
    # momentum: 0.9
    # weight_decay: 1e-4

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    num_epochs: 200
    decay_epoch: 100
  #   eta_min: 0 # min value for the lr
  #   last_epoch: -1
  #   verbose: False
